### ISSUE TITLE
1.1.2 Probable innacurate description of statement const size = 2;

### ISSUE THREAD

**Issue by pakmans** [source-academy/sicp#166]
Regarding the statement

`const size = 2;`

It says 

> The JavaScript specification demands that the special value undefined shall be the result of evaluating such constant declarations.

But that is a statement and not an expression, and thus has no value.
That the browser's REPL prints undefined after evaluating it is a different matter, I think.
If it actually evaluated to undefined you could assign it or pass it around (the whole statement and not the name of the constant), which you can not.

**Comment by martin-henz** [comment]
Yes, and no. 

The REPL displays the result of evaluating statements. That's why the evaluation of expression statements yields the value of the expression. The result of evaluating declarations is undefined.

But you are right in saying that we cannot bind the result value to any name, so the textbook comment requires more clarification.

How should we re-formulate to make this all clearer? 

To consider: This is a minor point, so the textbook should not be overly verbose about the issue.

**Comment by martin-henz** [comment]
Actually, JS does specify that expression statements are evaluated to the value of the expression, and that declaration statements are evaluated to undefined. JavaScript also specifies that loops evaluate to particular values...
