### ISSUE TITLE
3.5.1: Text not changed from Lisp

### ISSUE THREAD

**Issue by tfritzon** [source-academy/sicp#326]
In https://source-academy.github.io/sicp/split/chapters/3.5.1.html#p7

The text claims that "This expression does find the second prime, but the computational overhead is outrageous." which is true for Lisp, but in JavaScript we get a stack overflow.

```
head(tail(filter(is_prime,
                 enumerate_interval(10000, 1000000))));
```

```
Line 28: RangeError: Maximum call stack size exceeded
```

**Comment by martin-henz** [comment]
Well, Lisp will also encounter a stack overflow for this example, with the given recursive implementation of enumerate_interval. I think the authors didn't actually mean that the expression finds the second prime in practice. The assumption would be a stack size of 990000.

But you are right: Curious students will click and find that the error does not match the description.

I'm proposing that we make this program non-clickable, and keep the text, see PR. Can you review the PR @tfritzon to see if you agree with this take on it.

My argument is that this issue is not any different between Lisp and JavaScript and thus the text should not change.

**Comment by tfritzon** [comment]
Yes, that sounds like the best approach.
