### ISSUE TITLE
WEB: Search buttons: only web edition

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#338]
I've set up htmlContent such that the split edition is searched when one visits the split edition and the js edition is searched when one visits the js edition.

The trouble is that in htmlContent, the variable version is always undefined in lines 200, 215 and 220.

I can't figure out why.

**Comment by gerhean** [comment]
I don't believe that the variable version is at any point undefined in lines 200, 215 and 220. Searching the function `html_links_part2` shows that an nonempty string is always passed in the `version` parameter.

Rather, running `yarn split` actually calls `parseXmlHtml` in the file `\sicp\parseXmlHtml`, instead of `parseXmlHtml` in the file `\javascript\parseXmlHtml_split`

**Comment by martin-henz** [comment]
Any solution to this @gerhean ?
