### ISSUE TITLE
PDF edition: arrows for clicking programs in the margin

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#348]
when programs are intented:

<img width="875" alt="Screenshot 2020-07-23 at 2 30 55 PM" src="https://user-images.githubusercontent.com/30220768/88257929-7b894600-ccf1-11ea-8cdf-a1e8c4b117f2.png">

<img width="875" alt="Screenshot 2020-07-23 at 2 32 14 PM" src="https://user-images.githubusercontent.com/30220768/88257943-817f2700-ccf1-11ea-9dc3-371536272076.png">

Do we need these arrows in the PDF?

**Comment by TobiasWrigstad** [comment]
What do you mean by "when programs are intented"? 

Making the entire code block a hyperlink is not easy without affecting certain formatting aspects, such as the ability to have page breaks in blocks. The previous solution attempted to remedy this by breaking code blocks into several units where only the first was clickable. 

By moving the hyperlink to just one place (and making it look similar to the web version) this problem is avoided. 

How would you like clickable programs to render?

**Comment by TobiasWrigstad** [comment]
Some history documentation here for future ref: 

1) The current implementation simply "jumps X cm" before printing an arrow inside a 0pt box, and then jumps back X cm before rendering the rest of the line -- this is what causes the error as not all listings start at the same hoffset. 
2) Using marginpar to put the arrow in the margin causes LaTeX to die because there are too many floats (all parts handled as floats internally); increasing the float space cases floats to get lost completely. 
3) Using marginnote to avoid the marginpar problem causes the listing environment to flow into the margin, and also introduces a voffset error that sometimes causes the arrow and the code block to ends up on different pages.
