### ISSUE TITLE
Unable to Run "yarn pdf" Command

### ISSUE THREAD

**Issue by sarahgoh97** [source-academy/sicp#355]
Hello, I am trying to make a different adaptation of the SICP book. To start, I decided to compile without editing the files. The "yarn" and "yarn install" commands have worked on Git Bash. However, when I tried to use "yarn pdf", I keep getting the same Latex error in sicpjs.log: 

! LaTeX Error: Unknown graphics extension: .svg. 

I will get sicpjs.pdf as an output. However, comparing with the original pdf version, all the graphics with the .svg extension were skipped over. I am currently using a Windows laptop. I have tried using MikTex and TexLive (2020) but they have not worked. I could not find a 2017 version of TexLive which was mentioned in the Wiki page. 

Am I missing a package or an installation when trying to run the command "yarn pdf"? Or is this a Windows problem (since it worked on an OpenSuse VM which used TexLive 2017)?

Thank you!

**Comment by TobiasWrigstad** [comment]
Sounds like a bug where an image is believed to have an .svg extension instead of .pdf. All the files have the extension name ".svg.pdf" (which is not really great). Maybe this is not supported on Windows? Can you try locally and rename the first file where the error appears (in .tex and in the file system) to just ".pdf" and see if that solves the problem?

**Comment by sarahgoh97** [comment]
I tried renaming the ch1-Z-G-1.svg.pdf file in sicp > docs_out > img_javascript but the error has not changed. Am I changing the wrong file?

This is the exact error that I see: 

\openout3 = `sicpjs-4.cpt'.

(./sicpjs-4.cpt)) (./chapter1/section1/subsection3.tex [25]

! LaTeX Error: Unknown graphics extension: .svg.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.24 ....8]{{img\string_javascript/ch1-Z-G-1}.svg}
                                                  }
Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

)

I also checked the output pdf file, the first svg file did not show up too.

**Comment by TobiasWrigstad** [comment]
Did you change line 24 from this 
```
\maxsizebox{\linewidth}{0.8\paperheight}{\includegraphics[scale=0.8]{{img\string_javascript/ch1-Z-G-1}.svg}}
```
to 
```
\maxsizebox{\linewidth}{0.8\paperheight}{\includegraphics[scale=0.8]{{img\string_javascript/ch1-Z-G-1}.pdf}}
```
?

**Comment by TobiasWrigstad** [comment]
PDFLaTeX should append one of its supported suffixes for inclusion, e.g. `.pdf` for PDFs, `.png` or `.jpg`. But I suspect it is confused because there is a `ch1-Z-G-1.svg`file as well in place. 

Please change line 24 and try again. First try to change it to this: 
```
\maxsizebox{\linewidth}{0.8\paperheight}{\includegraphics[scale=0.8]{{img\string_javascript/ch1-Z-G-1}.svg.pdf}}
```
If that works, then the easiest solution is probably to change the JavaScript processor that outputs LaTeX to append a `.pdf` on all `.svg` file ends. 

If that does not work, try changing to this:
```
\maxsizebox{\linewidth}{0.8\paperheight}{\includegraphics[scale=0.8]{{img\string_javascript/ch1-Z-G-1}.pdf}}
```
If that works, then we can change the file names to `.pdf` instead of `.svg.pdf`. That is probably the best solution, but also the one that is the most tedious.

**Comment by sarahgoh97** [comment]
It works when I change it to

\maxsizebox{\linewidth}{0.8\paperheight}{\includegraphics[scale=0.8]{{img\string_javascript/ch1-Z-G-1}.svg.pdf}}

How do I change the JavaScript processor?

**Comment by TobiasWrigstad** [comment]
Ok, that's great.

**Comment by TobiasWrigstad** [comment]
Look at `sicp/javascript/processingFunctions/processFigurePdf.js`. It seems this function is doing the work here. 

```
export const generateImage = imagePath => {
  return (
    "\n\\maxsizebox{\\linewidth}{0.8\\paperheight}{" +
    "\\includegraphics[scale=0.8]{{" +
    imagePath
      .replace(/\.gif$/, ".png")
      .replace(/\.(?=[^.]*$)/, "}.")
      .replace(/_/g, "\\string_") +
    "}}"
  );
};
```

**Comment by TobiasWrigstad** [comment]
What you need to do is to *add* `.pdf` to only those figures whose `imagePath` ends with `.svg`.

**Comment by sarahgoh97** [comment]
Thank you! It works now 👍

**Comment by sarahgoh97** [comment]
For future reference, I changed your code snippet starting from line 48 to:

export const generateImage = imagePath => {
  return (
    "\n\\maxsizebox{\\linewidth}{0.8\\paperheight}{" +
    "\\includegraphics[scale=0.8]{{" +
    imagePath
      .replace(/\.gif$/, ".png")
      .replace(/\.(?=[^.]*$)/, "}.")
      .replace(/_/g, "\\string_")
      .replace(/svg/, "svg.pdf") +
    "}}"
  );
};

**Comment by TobiasWrigstad** [comment]
Great!
