### ISSUE TITLE
Error generating epub

### ISSUE THREAD

**Issue by yosevu** [source-academy/sicp#434]
Hello, 

I tried running `yarn epub` and ran into the error below. Is there another way to access the epub version?

Thanks!

```
chapter5/section4/subsection4.xml

Error at "source" (line 369, column 17):
unexpected ()
\begin{document}
                ^
error Command failed with exit code 65.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by martin-henz** [comment]
The epub version is not supported any longer. Sorry.

**Comment by FeeJai** [comment]
That is unfortunate, is there any chance we could contribute and start support again?

**Comment by fwuensche** [comment]
Hey, thanks for the project! I just faced the same issue and I actually spent a whole morning on it since the docs and the codebase indicate that epub is a supported format. Would it be too much work for you to show us how to contribute and fix the epub issues? Or should we rather just remove all references to epub from the wiki, readme, and the codebase?
