### ISSUE TITLE
PDF: formulas slightly misaligned

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#470]
All formulas should start at the same horizontal position. That's currently not the case, due to the difference in padding around align* and array environments.

**Comment by TobiasWrigstad** [comment]
My suggestion is that all formulas which are visible at the same time start at the same horizontal position. Currently, we sometimes have a few mm off due to spacing differences between equation* and align*. 

I'll see if there is a simple way around that using a global setting but if not, I think it is fine to make sure it is observably (on a single spread) consistent. 

How do you feel about that?

**Comment by martin-henz** [comment]
Yes, as long as it looks ok on a single page spread, I think it's fine.

**Comment by martin-henz** [comment]
I forgot: What do we need align* for, anyway? Can we not replace all of those align* by array?
