### ISSUE TITLE
SVG: Keywords in figures in 3.2

### ISSUE THREAD

**Issue by martin-henz** [source-academy/sicp#479]
The JavaScript keywords (return, if, else) should be in bold font.

**Comment by martin-henz** [comment]
Sorry @TobiasWrigstad for messing up the fonts in this PR. Do you think you can fix them as discussed, keeping them consistent with the snippets in the text?

Do note the Times fonts for E1, E2 etc. I'm quite keen on those, instead of Mono, to make it consistent with the text.

**Comment by TobiasWrigstad** [comment]
No problem! I will fix.

**Comment by TobiasWrigstad** [comment]
Turned out to be very little to fix. Because of the lack of a bold face in Latin Modern Mono @ Normal and our decision to keep the fonts as-is, we are "stuck" with Latin Modern Mono Light @ Bold for the bold face. It seems consistent with the text. 

I have made some small changes here and there to line heights. Merging now.
