### ISSUE TITLE
Web: Scrolling order inconsistent with table of contents for 'Acknowledgements'

### ISSUE THREAD

**Issue by chrisjwelly** [source-academy/sicp#84]
### Issue
When scrolling down the [Acknowledgements](https://sicp.comp.nus.edu.sg/chapters/87) section, it jumps straight to the References section.

### Expected behaviour
In the table of contents, Acknowledgements is followed by Chapter 1. As a user, this makes me expect to be led to Chapter 1 as I finish the Acknowledgements section, instead of being led to the References section.

### Additional remarks
I am not sure if this is an intended behaviour. The link to Acknowledgements is suffixed with /87 (https://sicp.comp.nus.edu.sg/chapters/87), while References is suffixed with /88. With respect to this, the behaviour is not surprising. However, it could be confusing to users because of the inconsistency with the table of contents.

**Comment by martin-henz** [comment]
Sectioning needs major re-vamp. Note the odd naming of sections, such as `99making99.xml` in order to get sections such as Preface, Acknowledgments and References to line up properly. I will not have the time to take a closer look at this, so for now, we are stuck with the current state of affairs, which has this Issue as a minor consequence.

Anyone is welcome to re-vamp the generation of the Web Edition. Volunteers needed!

**Comment by eksinyue** [comment]
The sections have been re-ordered in the new web edition.
